import type { CatalogItem } from './contracts.js';

/** Generic shared deliverable defaults from the founder's original catalog.
 * Source: https://org-manager-console.lovable.app/work-logs, Catalog tab.
 * PMO-authorized capture: 2026-09-05T00:51:01.890Z; 124 Shared rows, zero local overrides.
 * Transfer: compact source entries 15542 ASCII characters, FNV-1a32 356e2b3f.
 * These values are from the approved shared UI capture, not repository migration seeds.
 * Only code, name, category and reference hours were transcribed; no private workspace data.
 */
export const BUNDLED_TIME_CATALOG: readonly Omit<CatalogItem, 'origin' | 'version'>[] = [
  {
    code: 'account-research-list-50-accounts',
    name: 'Account research list (50 accounts)',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'admin-tasks-bundle-of-10',
    name: 'Admin tasks (bundle of 10)',
    category: 'Finance & Back Office',
    referenceTenths: 40,
  },
  {
    code: 'agenda-run-of-show',
    name: 'Agenda / run of show',
    category: 'Event Agency',
    referenceTenths: 80,
  },
  {
    code: 'analysis-with-findings',
    name: 'Analysis with findings',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'analyst-briefing-prepared-held',
    name: 'Analyst briefing (prepared + held)',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'annual-budget',
    name: 'Annual budget',
    category: 'Finance & Back Office',
    referenceTenths: 400,
  },
  {
    code: 'annual-financial-statements-per-entity',
    name: 'Annual financial statements (per entity)',
    category: 'Finance & Back Office',
    referenceTenths: 400,
  },
  {
    code: 'board-reporting-pack',
    name: 'Board reporting pack',
    category: 'Finance & Back Office',
    referenceTenths: 200,
  },
  {
    code: 'brand-package-guidelines-core-assets',
    name: 'Brand package (guidelines, core assets)',
    category: 'Marketing Agency',
    referenceTenths: 400,
  },
  {
    code: 'briefing-deck',
    name: 'Briefing deck',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'bug-fix',
    name: 'Bug fix',
    category: 'Software Agency',
    referenceTenths: 40,
  },
  {
    code: 'business-review',
    name: 'Business review',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'campaign-concept',
    name: 'Campaign concept',
    category: 'Marketing Agency',
    referenceTenths: 200,
  },
  {
    code: 'campaign-setup-structure-ads-tracking',
    name: 'Campaign setup (structure, ads, tracking)',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'certification-assessment',
    name: 'Certification / assessment',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'client-steering-meeting-prepared-held',
    name: 'Client steering meeting (prepared + held)',
    category: 'Management & Leadership',
    referenceTenths: 40,
  },
  {
    code: 'clipping-report',
    name: 'Clipping report',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'closed-deal-enterprise',
    name: 'Closed deal (enterprise)',
    category: 'Sales Organization',
    referenceTenths: 800,
  },
  {
    code: 'closed-deal-mid-market',
    name: 'Closed deal (mid-market)',
    category: 'Sales Organization',
    referenceTenths: 400,
  },
  {
    code: 'closed-deal-smb',
    name: 'Closed deal (SMB)',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'closed-renewal',
    name: 'Closed renewal',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'community-event-ama-organized-run',
    name: 'Community event / AMA (organized, run)',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'competitive-battlecard',
    name: 'Competitive battlecard',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'competitive-intel-report',
    name: 'Competitive intel report',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'contract-drafted-from-playbook',
    name: 'Contract drafted from playbook',
    category: 'Finance & Back Office',
    referenceTenths: 80,
  },
  {
    code: 'contract-review-standard-redlined',
    name: 'Contract review (standard, redlined)',
    category: 'Finance & Back Office',
    referenceTenths: 40,
  },
  {
    code: 'country-compliance-brief',
    name: 'Country compliance brief',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'creative-test-cycle',
    name: 'Creative test cycle',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'crm-workflow-automation-built-tested',
    name: 'CRM workflow / automation (built, tested)',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'custom-technical-demo',
    name: 'Custom technical demo',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'customer-webinar',
    name: 'Customer webinar',
    category: 'Customer Success & Support',
    referenceTenths: 40,
  },
  {
    code: 'dashboard-built-validated',
    name: 'Dashboard (built, validated)',
    category: 'Software Agency',
    referenceTenths: 200,
  },
  {
    code: 'data-pipeline-new-source',
    name: 'Data pipeline (new source)',
    category: 'Software Agency',
    referenceTenths: 200,
  },
  {
    code: 'delivery-timeline-budget-risks',
    name: 'Delivery timeline, budget & risks',
    category: 'Event Agency',
    referenceTenths: 80,
  },
  {
    code: 'demo-delivered',
    name: 'Demo delivered',
    category: 'Sales Organization',
    referenceTenths: 20,
  },
  {
    code: 'design-package-feature-all-states',
    name: 'Design package (feature, all states)',
    category: 'Product & Design Studio',
    referenceTenths: 200,
  },
  {
    code: 'design-system-component',
    name: 'Design system component',
    category: 'Product & Design Studio',
    referenceTenths: 80,
  },
  {
    code: 'device-account-on-offboarding-per-employee',
    name: 'Device & account on-/offboarding (per employee)',
    category: 'Software Agency',
    referenceTenths: 40,
  },
  {
    code: 'discovery-study-problem-validated',
    name: 'Discovery study (problem validated)',
    category: 'Product & Design Studio',
    referenceTenths: 200,
  },
  {
    code: 'employment-contract-issued',
    name: 'Employment contract issued',
    category: 'HR & Recruiting',
    referenceTenths: 20,
  },
  {
    code: 'eor-onboarding-per-hire-country',
    name: 'EOR onboarding (per hire & country)',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'escalation-decision-memo',
    name: 'Escalation / decision memo',
    category: 'Management & Leadership',
    referenceTenths: 40,
  },
  {
    code: 'escalation-resolved',
    name: 'Escalation resolved',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'event-concept-objectives-scope',
    name: 'Event concept (objectives & scope)',
    category: 'Event Agency',
    referenceTenths: 80,
  },
  {
    code: 'go-live-cutover',
    name: 'Go-live / cutover',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'hire-offer-accepted',
    name: 'Hire (offer accepted)',
    category: 'HR & Recruiting',
    referenceTenths: 400,
  },
  {
    code: 'incident-resolved-incl-postmortem',
    name: 'Incident resolved (incl. postmortem)',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'infrastructure-change-reviewed-applied',
    name: 'Infrastructure change (reviewed, applied)',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'interview-study-5-interviews-synthesized',
    name: 'Interview study (5 interviews, synthesized)',
    category: 'Product & Design Studio',
    referenceTenths: 200,
  },
  {
    code: 'jour-fixe-prepared-held-minutes-actions',
    name: 'Jour fixe (prepared, held, minutes + actions)',
    category: 'Management & Leadership',
    referenceTenths: 20,
  },
  {
    code: 'journalist-pitch',
    name: 'Journalist pitch',
    category: 'Marketing Agency',
    referenceTenths: 20,
  },
  {
    code: 'knowledge-base-article',
    name: 'Knowledge-base article',
    category: 'Customer Success & Support',
    referenceTenths: 20,
  },
  {
    code: 'launch-package-messaging-assets-brief',
    name: 'Launch package (messaging, assets, brief)',
    category: 'Marketing Agency',
    referenceTenths: 400,
  },
  {
    code: 'localized-process-doc',
    name: 'Localized process doc',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'long-form-article',
    name: 'Long-form article',
    category: 'Product & Design Studio',
    referenceTenths: 80,
  },
  {
    code: 'media-list',
    name: 'Media list',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'monthly-close-per-entity',
    name: 'Monthly close (per entity)',
    category: 'Finance & Back Office',
    referenceTenths: 200,
  },
  {
    code: 'monthly-close-support-per-market',
    name: 'Monthly close support (per market)',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'monthly-community-report',
    name: 'Monthly community report',
    category: 'Marketing Agency',
    referenceTenths: 20,
  },
  {
    code: 'monthly-forecast-update',
    name: 'Monthly forecast update',
    category: 'Finance & Back Office',
    referenceTenths: 80,
  },
  {
    code: 'monthly-ic-contract-review-kpis-proof-of-performance-vs-billing',
    name: 'Monthly IC contract review (KPIs, proof of performance vs. billing)',
    category: 'Management & Leadership',
    referenceTenths: 40,
  },
  {
    code: 'monthly-performance-report',
    name: 'Monthly performance report',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'monthly-reporting-pack',
    name: 'Monthly reporting pack',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'monthly-sla-report',
    name: 'Monthly SLA report',
    category: 'Software Agency',
    referenceTenths: 40,
  },
  {
    code: 'negotiated-uplift',
    name: 'Negotiated uplift',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'new-joiner-onboarding-day-1-ready',
    name: 'New-joiner onboarding (day-1 ready)',
    category: 'HR & Recruiting',
    referenceTenths: 40,
  },
  {
    code: 'offsite-meeting-logistics',
    name: 'Offsite / meeting logistics',
    category: 'Finance & Back Office',
    referenceTenths: 80,
  },
  {
    code: 'onboarding-workshop',
    name: 'Onboarding workshop',
    category: 'Customer Success & Support',
    referenceTenths: 40,
  },
  {
    code: 'one-pager-datasheet',
    name: 'One-pager / datasheet',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'owner-round-weekly',
    name: 'Owner round (weekly)',
    category: 'Management & Leadership',
    referenceTenths: 20,
  },
  {
    code: 'partner-agreement-signed',
    name: 'Partner agreement signed',
    category: 'Sales Organization',
    referenceTenths: 400,
  },
  {
    code: 'partner-enablement-kit',
    name: 'Partner enablement kit',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'partner-sourced-deal-registered',
    name: 'Partner-sourced deal registered',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'pentest-scoped-with-report',
    name: 'Pentest (scoped, with report)',
    category: 'Software Agency',
    referenceTenths: 400,
  },
  {
    code: 'playbook-template',
    name: 'Playbook / template',
    category: 'Finance & Back Office',
    referenceTenths: 200,
  },
  {
    code: 'poc-scoped-run-evaluated',
    name: 'PoC (scoped, run, evaluated)',
    category: 'Sales Organization',
    referenceTenths: 200,
  },
  {
    code: 'policy-process-doc',
    name: 'Policy / process doc',
    category: 'HR & Recruiting',
    referenceTenths: 40,
  },
  {
    code: 'positioning-messaging-doc',
    name: 'Positioning & messaging doc',
    category: 'Marketing Agency',
    referenceTenths: 200,
  },
  {
    code: 'prd-feature-spec',
    name: 'PRD / feature spec',
    category: 'Product & Design Studio',
    referenceTenths: 200,
  },
  {
    code: 'press-release',
    name: 'Press release',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'produced-video',
    name: 'Produced video',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'project-coordination-per-client-project-per-sprint',
    name: 'Project coordination (per client project, per sprint)',
    category: 'Management & Leadership',
    referenceTenths: 80,
  },
  {
    code: 'proposal-delivered',
    name: 'Proposal delivered',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'qbr-prepared-held',
    name: 'QBR (prepared + held)',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'qualified-candidate-slate-3-screened',
    name: 'Qualified candidate slate (3 screened)',
    category: 'HR & Recruiting',
    referenceTenths: 80,
  },
  {
    code: 'qualified-meeting-booked-held',
    name: 'Qualified meeting (booked & held)',
    category: 'Sales Organization',
    referenceTenths: 40,
  },
  {
    code: 'qualified-opportunity',
    name: 'Qualified opportunity',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'quarterly-renewal-board-per-portfolio',
    name: 'Quarterly renewal board (per portfolio)',
    category: 'Management & Leadership',
    referenceTenths: 80,
  },
  {
    code: 'quarterly-roadmap-update',
    name: 'Quarterly roadmap update',
    category: 'Product & Design Studio',
    referenceTenths: 80,
  },
  {
    code: 'regression-run-report',
    name: 'Regression run + report',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'release-packaged-notes-deployed',
    name: 'Release (packaged, notes, deployed)',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'release-acceptance-protocol',
    name: 'Release acceptance protocol',
    category: 'Software Agency',
    referenceTenths: 40,
  },
  {
    code: 'rfi-response',
    name: 'RFI response',
    category: 'Marketing Agency',
    referenceTenths: 200,
  },
  {
    code: 'rfp-security-questionnaire',
    name: 'RFP / security questionnaire',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'sales-deck',
    name: 'Sales deck',
    category: 'Marketing Agency',
    referenceTenths: 80,
  },
  {
    code: 'security-incident-response',
    name: 'Security incident response',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'security-review-feature-system',
    name: 'Security review (feature/system)',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'single-creative-asset',
    name: 'Single creative asset',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'single-screen-asset',
    name: 'Single screen / asset',
    category: 'Product & Design Studio',
    referenceTenths: 40,
  },
  {
    code: 'sprint-planning-review-per-corporation-per-sprint',
    name: 'Sprint planning & review (per corporation, per sprint)',
    category: 'Management & Leadership',
    referenceTenths: 80,
  },
  {
    code: 'standard-onboarding-per-customer',
    name: 'Standard onboarding (per customer)',
    category: 'Customer Success & Support',
    referenceTenths: 400,
  },
  {
    code: 'success-plan-per-account',
    name: 'Success plan (per account)',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'support-tickets-bundle-of-10',
    name: 'Support tickets (bundle of 10)',
    category: 'Software Agency',
    referenceTenths: 40,
  },
  {
    code: 'survey-designed-fielded-analyzed',
    name: 'Survey (designed, fielded, analyzed)',
    category: 'Product & Design Studio',
    referenceTenths: 80,
  },
  {
    code: 't1-tickets-bundle-of-10',
    name: 'T1 tickets (bundle of 10)',
    category: 'Customer Success & Support',
    referenceTenths: 40,
  },
  {
    code: 't2-escalated-ticket',
    name: 'T2 / escalated ticket',
    category: 'Customer Success & Support',
    referenceTenths: 20,
  },
  {
    code: 'tax-filing-per-filing',
    name: 'Tax filing (per filing)',
    category: 'Finance & Back Office',
    referenceTenths: 80,
  },
  {
    code: 'technical-spike-poc',
    name: 'Technical spike / PoC',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'territory-quota-model',
    name: 'Territory & quota model',
    category: 'Sales Organization',
    referenceTenths: 200,
  },
  {
    code: 'test-plan-per-release',
    name: 'Test plan (per release)',
    category: 'Software Agency',
    referenceTenths: 80,
  },
  {
    code: 'tool-fleet-rollout',
    name: 'Tool / fleet rollout',
    category: 'Software Agency',
    referenceTenths: 200,
  },
  {
    code: 'training-module',
    name: 'Training module',
    category: 'Customer Success & Support',
    referenceTenths: 80,
  },
  {
    code: 'training-module-single-session',
    name: 'Training module (single session)',
    category: 'Sales Organization',
    referenceTenths: 80,
  },
  {
    code: 'training-program',
    name: 'Training program',
    category: 'Customer Success & Support',
    referenceTenths: 400,
  },
  {
    code: 'training-program-curriculum-materials',
    name: 'Training program (curriculum + materials)',
    category: 'Sales Organization',
    referenceTenths: 400,
  },
  {
    code: 'travel-arrangement-per-trip',
    name: 'Travel arrangement (per trip)',
    category: 'Finance & Back Office',
    referenceTenths: 20,
  },
  {
    code: 'usability-test-run-findings',
    name: 'Usability test (run + findings)',
    category: 'Product & Design Studio',
    referenceTenths: 80,
  },
  {
    code: 'user-story-accepted-incl-tests',
    name: 'User story (accepted, incl. tests)',
    category: 'Software Agency',
    referenceTenths: 200,
  },
  {
    code: 'ux-copy-set-per-feature',
    name: 'UX copy set (per feature)',
    category: 'Product & Design Studio',
    referenceTenths: 40,
  },
  {
    code: 'venue-logistics-plan',
    name: 'Venue & logistics plan',
    category: 'Event Agency',
    referenceTenths: 200,
  },
  {
    code: 'verified-bug-report',
    name: 'Verified bug report',
    category: 'Software Agency',
    referenceTenths: 20,
  },
  {
    code: 'website-page-copy',
    name: 'Website page copy',
    category: 'Product & Design Studio',
    referenceTenths: 40,
  },
  {
    code: 'weekly-moderation-engagement',
    name: 'Weekly moderation & engagement',
    category: 'Marketing Agency',
    referenceTenths: 40,
  },
  {
    code: 'weekly-status-report-per-client-project',
    name: 'Weekly status report (per client project)',
    category: 'Management & Leadership',
    referenceTenths: 20,
  },
];
