import type { CompanyDefinition, TemplateSummary } from '../domain/contracts.js';
import { DomainError } from '../domain/errors.js';
import { validateDefinition } from '../domain/model.js';

const departments = [
  { name: 'Strategy & Operations', mission: 'Turn a founder brief into a bounded delivery program with clear owners and acceptance criteria.', output: 'a delivery brief with milestones, risks, owners and decisions', roles: ['Studio Director','Delivery Manager','Operations Analyst','Capacity Planner','Risk Analyst','Program Coordinator','Decision Researcher','Workflow Designer','Handoff Coordinator','Performance Analyst'] },
  { name: 'Product', mission: 'Understand the user problem and define a small, testable product outcome.', output: 'a product specification with user journeys and acceptance criteria', roles: ['Product Lead','Product Analyst','User Researcher','Requirements Analyst','Journey Designer','Backlog Curator','Experiment Designer','Product Metrics Analyst','Competitive Researcher','Acceptance Reviewer'] },
  { name: 'Design', mission: 'Create coherent and accessible product interactions grounded in the product brief.', output: 'a reviewable interface specification with states, copy and keyboard behavior', roles: ['Design Lead','Interaction Designer','Visual Designer','Design Systems Designer','Content Designer','Accessibility Designer','Prototype Designer','Information Architect','Usability Analyst','Design QA Reviewer'] },
  { name: 'Frontend Engineering', mission: 'Deliver maintainable interfaces with accessible states and predictable behavior.', output: 'a scoped frontend implementation plan and reviewable changes with tests', roles: ['Frontend Lead','UI Engineer','React Engineer','State Management Engineer','CSS Engineer','Accessibility Engineer','Frontend Test Engineer','Performance Engineer','Browser Compatibility Engineer','Frontend Reviewer'] },
  { name: 'Platform Engineering', mission: 'Build reliable data boundaries and small, observable local services.', output: 'a platform implementation or technical design with persistence and recovery checks', roles: ['Platform Lead','API Engineer','Data Model Engineer','SQLite Engineer','Migration Engineer','CLI Engineer','Configuration Engineer','Reliability Engineer','Backend Test Engineer','Platform Reviewer'] },
  { name: 'Integrations', mission: 'Connect supported tools through explicit contracts and verifiable execution evidence.', output: 'an integration contract or execution report separating configuration from runtime results', roles: ['Integrations Lead','Adapter Engineer','Protocol Engineer','Runtime Researcher','Authentication Specialist','Retry Engineer','Integration Test Engineer','Webhook Engineer','Tooling Engineer','Integration Reviewer'] },
  { name: 'Quality & Security', mission: 'Challenge delivery claims with tests, threat analysis and clear reproduction steps.', output: 'a prioritized test or security report with evidence and actionable findings', roles: ['Quality Lead','Test Strategist','Security Reviewer','Regression Engineer','Privacy Reviewer','Dependency Auditor','End-to-end Test Engineer','Failure Analyst','Accessibility Tester','Release QA Reviewer'] },
  { name: 'Developer Experience', mission: 'Make installation, learning, contribution and recovery straightforward.', output: 'tested setup instructions, a tutorial or a support runbook', roles: ['Developer Experience Lead','Technical Writer','Documentation Engineer','Tutorial Author','Example Maintainer','CLI UX Reviewer','Support Analyst','Onboarding Designer','Contribution Guide Author','Documentation Tester'] },
  { name: 'Research & Insights', mission: 'Answer bounded research questions using sources and calibrated conclusions.', output: 'a cited research memo distinguishing evidence, inference and open questions', roles: ['Research Lead','Technical Researcher','Market Researcher','Source Verifier','Data Analyst','Methods Reviewer','Trend Analyst','Interview Synthesizer','Evidence Librarian','Research Editor'] },
  { name: 'Release & Maintenance', mission: 'Package tested changes and keep support, rollback and maintenance practical.', output: 'a release checklist, artifact verification report or maintenance plan', roles: ['Release Lead','Build Engineer','CI Engineer','Package Maintainer','Release Notes Editor','Upgrade Tester','Backup Recovery Tester','Issue Triager','Maintenance Planner','Release Auditor'] },
] as const;

// Each role has an explicit deliverable boundary, not just a different display name.
const roleScopes = [
  ['Set company priorities, resolve cross-department tradeoffs and approve evidence-backed delivery milestones', 'Turn scope into a sequenced delivery plan and track acceptance blockers', 'Identify operational bottlenecks from available evidence and propose measurable improvements', 'Compare requested work with configured capacity and propose realistic sequencing', 'Maintain a risk register with owners, evidence, mitigations and decision dates', 'Track dependency handoffs and keep delivery commitments traceable', 'Prepare decision options with evidence, costs and reversible next steps', 'Document repeatable intake, review and delivery workflows', 'Prepare complete handoffs with artifacts, owners and remaining work', 'Define useful throughput and quality measures without inventing activity'],
  ['Own product outcomes and prioritize the smallest useful deliverable', 'Translate user needs into testable requirements and open questions', 'Design research questions and synthesize supplied user evidence without inventing interviews', 'Check requirements for ambiguity, contradictions and missing acceptance criteria', 'Map installation, onboarding, work and recovery journeys with failure states', 'Keep the backlog bounded, ordered and linked to user outcomes', 'Define experiments with hypotheses, success measures and stopping rules', 'Specify activation and retention measures with clear calculation boundaries', 'Compare relevant alternatives using attributable sources and explicit tradeoffs', 'Review delivered behavior against acceptance criteria and document gaps'],
  ['Set interface direction and review visual and interaction consistency', 'Specify task flows, confirmations, error handling and keyboard interactions', 'Refine typography, spacing, hierarchy and visual contrast', 'Maintain reusable tokens, primitives and interaction patterns', 'Write concise interface copy that describes actual behavior', 'Specify accessible focus, labels, contrast and reduced-motion behavior', 'Create reviewable interaction prototypes with meaningful states', 'Organize navigation and information hierarchy around user tasks', 'Analyze usability observations and propose specific improvements', 'Compare implemented screens with the approved design and report reproducible defects'],
  ['Own frontend architecture and review component boundaries and delivery quality', 'Implement interface components with loading, empty, error and success states', 'Build React components with stable state and predictable rendering', 'Design browser state transitions and concurrency-safe synchronization', 'Maintain responsive layout and reusable CSS without fragile overrides', 'Implement keyboard navigation, semantic controls and screen-reader announcements', 'Write frontend tests around observable behavior and meaningful regressions', 'Measure rendering and interaction performance on a documented workload', 'Verify browser-specific behavior and document supported combinations', 'Review frontend changes for correctness, accessibility and maintainability'],
  ['Own local service boundaries, reliability and technical acceptance', 'Specify and implement narrow API contracts with validation and clear errors', 'Define entity relationships, lifecycle invariants and version boundaries', 'Review SQLite transactions, constraints, indexes and concurrency behavior', 'Design migration journals, compatibility checks and pre-upgrade recovery', 'Build predictable command parsing, help, exit codes and startup behavior', 'Define explicit configuration precedence and safe defaults', 'Analyze crash recovery, resource cleanup and operational failure paths', 'Test persistence, migration and error handling using isolated databases', 'Review platform changes for data loss, invalid state and unnecessary complexity'],
  ['Choose supported integration paths and verify actual delivery evidence', 'Implement a narrow adapter around a documented external interface', 'Validate wire formats, event ordering and protocol error handling', 'Verify runtime installation, authentication and execution capabilities', 'Specify credential boundaries, owner authorization and token handling', 'Design idempotent retries and distinguish failure from uncertain delivery', 'Test dispatch, completion, failure, cancellation and restart behavior', 'Validate inbound event identity, deduplication and reply routing', 'Build inspectable setup diagnostics and integration examples', 'Review adapter behavior against its claimed runtime contract'],
  ['Set release acceptance criteria and prioritize correctness risks', 'Select tests that exercise meaningful boundaries and failure modes', 'Review threat boundaries, unsafe inputs and privilege assumptions', 'Reproduce defects and add focused regression coverage', 'Trace private data exposure, retention and external transfer boundaries', 'Review dependency provenance, licenses and known security findings', 'Verify the complete installed-product journey in a real browser', 'Turn failures into minimal reproductions and evidence-backed causes', 'Test keyboard, focus, labels, contrast and assistive-technology behavior', 'Audit release claims against reproducible acceptance evidence'],
  ['Own the first-run experience and remove developer setup friction', 'Explain product behavior and constraints in clear task-oriented prose', 'Keep documentation examples linked to tested code and current commands', 'Create step-by-step tutorials with observable completion checks', 'Maintain small runnable examples with explicit assumptions', 'Review command wording, defaults and recovery guidance', 'Convert support reports into reproducible issues and useful responses', 'Design first-company guidance that separates configuration from activation', 'Document contribution setup, boundaries, review and testing expectations', 'Execute documented examples and identify stale or missing instructions'],
  ['Frame bounded research questions and set source-quality standards', 'Investigate technical approaches using primary documentation and tests', 'Compare market alternatives without confusing claims with verified facts', 'Check citations, identities, dates and the claims each source supports', 'Analyze supplied datasets with stated methods and reproducible calculations', 'Challenge research methods, sampling assumptions and unsupported inference', 'Distinguish durable changes from noise using time-labelled evidence', 'Synthesize supplied interviews while preserving disagreements and uncertainty', 'Organize source references and evidence provenance for later review', 'Edit research into concise decisions, evidence and open questions'],
  ['Own release readiness, versioning and artifact acceptance', 'Produce reproducible builds and inspect their actual output contents', 'Maintain CI checks that cover supported runtimes and failure conditions', 'Review package files, installation behavior and dependency notices', 'Write release notes that distinguish shipped behavior from limitations', 'Verify upgrades from supported schemas and refusal of unsupported versions', 'Exercise backup, restore, interruption and corrupted-state recovery', 'Prioritize issues by reproducibility, impact and available evidence', 'Plan sustainable fixes, dependencies and recurring maintenance', 'Independently verify the installed release and its public claims'],
] as const;

export function listTemplates(): TemplateSummary[] {
  return [20, 100].map((count) => ({ id: `studio-${count}`, name: `${count}-agent Product Studio`, description: `A software delivery studio with 10 departments and ${count} distinct configured roles. Activation is optional and requires a supported external runtime.`, agentCount: count, departmentCount: 10 }));
}

export function getTemplate(id: string): CompanyDefinition {
  const summary = listTemplates().find((t) => t.id === id);
  if (!summary) throw new DomainError('NOT_FOUND', `Unknown company template: ${id}`);
  const now = new Date().toISOString();
  const companyId = 'template-studio'; const perDepartment = summary.agentCount / departments.length;
  const definition: CompanyDefinition = {
    schemaVersion: 1, name: summary.name, description: summary.description,
    companies: [{ id: companyId, name: 'Product Studio', shortCode: 'STUDIO', description: 'An independent software delivery studio organized around useful, verifiable work.', color: '#c96b43', status: 'active', version: 1, createdAt: now, updatedAt: now }],
    departments: [], agents: [], assignments: [], relationships: [],
  };
  for (const [departmentIndex, department] of departments.entries()) {
    const departmentId = `department-${departmentIndex}`; const leadId = `agent-${departmentIndex}-0`;
    definition.departments.push({ id: departmentId, companyId, name: department.name, description: department.mission, managerId: leadId });
    for (let roleIndex = 0; roleIndex < perDepartment; roleIndex += 1) {
      const agentId = `agent-${departmentIndex}-${roleIndex}`; const role = department.roles[roleIndex]!;
      const scope = roleScopes[departmentIndex]![roleIndex]!;
      definition.agents.push({
        id: agentId, name: role, role, kind: 'agent',
        instructions: `You are the ${role} in the ${department.name} department of Product Studio. ${department.mission} Your specific ownership: ${scope}. Work only within the assigned task and available tools. State assumptions and blockers; never invent access, completed execution, customer evidence or test results. Produce ${department.output}. Include evidence and clear next steps. ${roleIndex === 0 ? 'Coordinate department work, delegate bounded tasks and review acceptance evidence before reporting completion.' : `Hand your result to the ${department.roles[0]} with the evidence needed for review.`} External publishing, spending and communication require the operator's explicit authorization.`,
        responsibilities: [scope, department.mission, `Produce ${department.output}.`, 'Record sources, checks performed, remaining uncertainty and handoff details.'],
        departmentId, managerId: departmentIndex === 0 && roleIndex === 0 ? null : roleIndex === 0 ? 'agent-0-0' : leadId,
        status: 'active', version: 1, createdAt: now, updatedAt: now,
      });
      definition.assignments.push({ id: `assignment-${departmentIndex}-${roleIndex}`, agentId, companyId, isPrimary: true, startedAt: now, endedAt: null });
    }
  }
  return validateDefinition(definition);
}
